# coding=utf-8
"""
GitHub Issues Memory Backend - 使用 GitHub Issues 存储记忆数据

优势：
1. 持久化：数据存储在 GitHub，不会丢失
2. 免费：Issues 无限制
3. 可追溯：有完整的时间线
4. API 友好：易于读写
"""

import json
import os
import logging
from datetime import datetime, timedelta
from typing import Dict, List, Optional
import requests

logger = logging.getLogger(__name__)


class GitHubIssuesMemory:
    """使用 GitHub Issues 作为记忆后端"""
    
    def __init__(self, repo_owner: str, repo_name: str, token: str):
        """
        Args:
            repo_owner: GitHub 用户名或组织名
            repo_name: 仓库名称
            token: GitHub Personal Access Token (需要 repo 权限)
        """
        self.repo_owner = repo_owner
        self.repo_name = repo_name
        self.token = token
        self.base_url = f"https://api.github.com/repos/{repo_owner}/{repo_name}/issues"
        self.headers = {
            "Authorization": f"token {token}",
            "Accept": "application/vnd.github.v3+json"
        }
        
    def save_article_metadata(self, metadata: Dict) -> bool:
        """
        保存文章元数据到 Issue
        
        Args:
            metadata: 文章元数据
            
        Returns:
            是否成功
        """
        issue_data = {
            "title": f"[Memory] Article - {metadata['date']}",
            "body": self._format_issue_body(metadata),
            "labels": ["memory", "article-history"]
        }
        
        try:
            response = requests.post(
                self.base_url,
                headers=self.headers,
                json=issue_data,
                timeout=10
            )
            
            if response.status_code == 201:
                logger.warning(f"Issue created successfully: {response.json().get('html_url')}")
                return True
            else:
                logger.warning(f"Failed to create issue: {response.status_code} - {response.text[:200]}")
                return False
        except Exception as e:
            logger.warning(f"Error saving to GitHub Issues: {e}")
            return False
    
    def get_recent_articles(self, days: int = 7) -> List[Dict]:
        """
        获取最近的文章历史
        
        Args:
            days: 天数
            
        Returns:
            文章元数据列表
        """
        cutoff_date = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%d")
        
        try:
            # 搜索带有 memory 标签的 issues
            search_url = f"{self.base_url}?state=closed&labels=memory,article-history&per_page=100"
            response = requests.get(search_url, headers=self.headers, timeout=10)
            
            if response.status_code != 200:
                return []
            
            issues = response.json()
            articles = []
            
            for issue in issues:
                # 解析 body 中的元数据
                metadata = self._parse_issue_body(issue.get('body', ''))
                if metadata and metadata.get('date', '') >= cutoff_date:
                    articles.append(metadata)
            
            return articles
        except Exception as e:
            print(f"Error fetching from GitHub Issues: {e}")
            return []
    
    def generate_context_summary(self, days: int = 3) -> str:
        """生成近期热点背景摘要"""
        articles = self.get_recent_articles(days)
        
        if not articles:
            return "（无近期历史记录）"
        
        lines = [
            "## 📚 近期热点背景（供参考）\n",
            f"*以下信息来自过去{days}天的报道，帮助理解今日热点的延续性*\n"
        ]
        
        # 提取主要话题
        all_topics = {}
        for article in articles:
            for topic in article.get('hot_topics', []):
                if topic not in all_topics:
                    all_topics[topic] = []
                all_topics[topic].append(article['date'])
        
        # 持续关注的热点
        ongoing_topics = [
            topic for topic, dates in all_topics.items()
            if len(dates) >= 2
        ]
        
        if ongoing_topics:
            lines.append("\n### 🔥 持续关注的话题")
            for topic in ongoing_topics[:5]:
                dates = all_topics[topic]
                lines.append(f"- **{topic}**: 已连续{len(dates)}天出现在热点中")
        
        # 最近的重要事件
        lines.append("\n### 📅 近期重要事件回顾")
        for article in articles[:5]:
            lines.append(f"- **{article['date']}**: {article['title']}")
            if article.get('excerpt'):
                lines.append(f"  > {article['excerpt'][:80]}...")
        
        return "\n".join(lines)
    
    def _format_issue_body(self, metadata: Dict) -> str:
        """格式化 Issue body"""
        return f"""
## Article Metadata

**Date**: {metadata.get('date', '')}
**Title**: {metadata.get('title', '')}

**Keywords**: {', '.join(metadata.get('keywords', []))}

**Hot Topics**: {', '.join(metadata.get('hot_topics', []))}

**Platforms**: {', '.join(metadata.get('platforms', []))}

**Excerpt**:
{metadata.get('excerpt', '')}

---
*Auto-generated by TrendRadar Memory System*
**Timestamp**: {metadata.get('timestamp', '')}
"""
    
    def _parse_issue_body(self, body: str) -> Optional[Dict]:
        """从 Issue body 解析元数据"""
        try:
            metadata = {}
            
            # 简单解析（可以改进为更健壮的解析）
            lines = body.split('\n')
            for line in lines:
                if line.startswith('**Date**:') :
                    metadata['date'] = line.replace('**Date**:', '').strip()
                elif line.startswith('**Title**:'):
                    metadata['title'] = line.replace('**Title**:', '').strip()
                elif line.startswith('**Keywords**:'):
                    keywords_str = line.replace('**Keywords**:', '').strip()
                    metadata['keywords'] = [k.strip() for k in keywords_str.split(',') if k.strip()]
                elif line.startswith('**Hot Topics**:'):
                    topics_str = line.replace('**Hot Topics**:', '').strip()
                    metadata['hot_topics'] = [t.strip() for t in topics_str.split(',') if t.strip()]
                elif line.startswith('**Platforms**:'):
                    platforms_str = line.replace('**Platforms**:', '').strip()
                    metadata['platforms'] = [p.strip() for p in platforms_str.split(',') if p.strip()]
                elif line.startswith('**Excerpt**:'):
                    # 下一行是 excerpt
                    idx = lines.index(line)
                    if idx + 1 < len(lines):
                        metadata['excerpt'] = lines[idx + 1].strip()
            
            return metadata if metadata else None
        except Exception as e:
            print(f"Error parsing issue body: {e}")
            return None
